[build]
  base    = "site"                 # enter the Hugo site dir
  publish = "public"               # Hugo output dir
  command = "hugo --gc"		   # build with Hugo

[build.environment]
  HUGO_VERSION = "0.147.0"         # >= 0.146.0 for PaperMod
