baseurl = "https://www.geck0x.com/"
languageCode = "en-us"
languageLang = "en"
title = "Geck0x"
theme = "PaperMod"

disableKinds = ["RSS", "taxonomy"]

[params]
  images = ["img/geck0x-og.png"]
  env = "production"
  title = "Geck0x Crypto Blog"
  description = "A Crypto Safety Blog for Non-Cyborgs"
  author = "Geck0x"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShareButtons = ["x", "linkedin", "reddit", "facebook"]
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  comments = false
  homeInfoParams = false
  customCSS = ["css/custom.css"]
  # (NO logo params needed now)

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

